#ifndef VALORES_SIMULACAO_H
#define VALORES_SIMULACAO_H

#define NHABILIDADES 10 //original: 10
#define FIMMUNDO 100000 //original: 525600
#define NHEROIS NHABILIDADES * 5
#define NBASES NHEROIS / 5
#define NMISSOES FIMMUNDO / 100
#define TAMMUNDO 20000
#define NCOMPOSTOS NHABILIDADES * 3

#endif